language: go
go: 
 - 1.8.x
 - 1.9.x
 - 1.10.x
 - 1.11.4
install:
 - go get -u github.com/alecthomas/gometalinter
script:
 - gometalinter --install
 - gometalinter --config=./gometalinter.json --vendor ./...
 - go test -v ./...
